apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: ai-service
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-service
spec:
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: k8s-service
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  ports:
    - port: 8003
      targetPort: 8003
  selector:
    app: session-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: tool-server
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: tool-server
